name: Release Terraform Module

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          branch: main
          extra_plugins: |
            @semantic-release/git@9.0.0
            @semantic-release/github@7.1.1
            @semantic-release/changelog@5.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.MAINTAINER_GITHUB_ACCESS_TOKEN }}
